# Generated by Django 4.2.24 on 2025-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
